version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/" # Location of your mix.exs file
    schedule:
      interval: "daily" # Options: "daily", "weekly", "monthly"
    versioning-strategy: "lockfile-only"
